services:
  cutter-status-dashboard:
    build: 
      context: ./
      target: dev_environment
    entrypoint: CompileDaemon -log-prefix=false -build="env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o cutter-status-dashboard ." -command "./cutter-status-dashboard"
    links:
      - redis
    ports:
      - "0.0.0.0:8080:8080"
    volumes:
      - ~/.ssh:/root/.ssh
      - ./:/app
    environment:
      PORT: 8080
      REDIS_URL: redis:6379
      PLATFORM_ENDPOINT: 0.0.0.0:8081
  redis:
    image: redis:alpine